//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class URLResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal URLResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.URLResources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://localhost:65103.
        /// </summary>
        internal static string BASE_URI {
            get {
                return ResourceManager.GetString("BASE_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/Category/Applications/delete?id=.
        /// </summary>
        internal static string DELETE_APPLICATION {
            get {
                return ResourceManager.GetString("DELETE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/Category/Applications/get?id=.
        /// </summary>
        internal static string GET_APPLICATION {
            get {
                return ResourceManager.GetString("GET_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/Menu/getListByUser.
        /// </summary>
        internal static string GET_MENU {
            get {
                return ResourceManager.GetString("GET_MENU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/Users/login.
        /// </summary>
        internal static string LOGIN_API {
            get {
                return ResourceManager.GetString("LOGIN_API", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/Category/Applications/save.
        /// </summary>
        internal static string SAVE_APPLICATION {
            get {
                return ResourceManager.GetString("SAVE_APPLICATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to api/v1/Category/Applications/search.
        /// </summary>
        internal static string SEARCH_APPLICATION {
            get {
                return ResourceManager.GetString("SEARCH_APPLICATION", resourceCulture);
            }
        }
    }
}
